name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      # --- NEW STEPS START HERE ---
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test with pytest and generate coverage report
        run: pytest --cov=app --cov-report=xml
      # --- NEW STEPS END HERE ---

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
            # --- ADD THIS BLOCK ---
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
  # --------------------
    